// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usqlazbeqvgnimjlysox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzcWxhemJlcXZnbmltamx5c294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODgwMDAsImV4cCI6MjA2MDU2NDAwMH0.NQ-dxctfU5BnE7GqJQPduKTtdkyhGVyu47prYsKlc-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);